# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('BunqAPI', '0001_initial'), ('BunqAPI', '0002_auto_20170429_1040'), ('BunqAPI', '0003_profile_session_token'), ('BunqAPI', '0004_auto_20170517_1201'), ('BunqAPI', '0005_auto_20170517_1207'), ('BunqAPI', '0006_auto_20170517_1316'), ('BunqAPI', '0007_auto_20170517_1346'), ('BunqAPI', '0008_auto_20170517_1354'), ('BunqAPI', '0009_auto_20170517_1429'), ('BunqAPI', '0010_auto_20170517_1432'), ('BunqAPI', '0011_profile_invoice_token'), ('BunqAPI', '0012_proxy'), ('BunqAPI', '0013_profile_avatar_token'), ('BunqAPI', '0014_profile_payment_token'), ('BunqAPI', '0015_auto_20170601_1044'), ('BunqAPI', '0016_delete_proxy'), ('BunqAPI', '0017_remove_profile_invoice_token'), ('BunqAPI', '0018_profile_session_server_token'), ('BunqAPI', '0019_auto_20170605_1417'), ('BunqAPI', '0020_auto_20170605_1419'), ('BunqAPI', '0021_auto_20170605_1442'), ('BunqAPI', '0022_auto_20170607_2047')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.CharField(blank=True, max_length=150)),
                ('session_data', models.CharField(blank=True, max_length=150)),
                ('session_end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
