# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0001_squashed_0022_auto_20170607_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_file',
            new_name='session_server_token_and_user_id',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_data',
            new_name='session_token',
        ),
    ]
