# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='private_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='GUID',
            field=models.CharField(blank=True, max_length=68),
        ),
    ]
