# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0002_auto_20170429_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
