# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0002_auto_20170607_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_server_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
