# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0003_session_session_server_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_server_token_and_user_id',
            new_name='session_user_id',
        ),
        migrations.AddField(
            model_name='session',
            name='session_server_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
