# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0004_auto_20170608_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='new_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='old_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
