# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0004_auto_20170517_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='GUID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=68), blank=True, size=2),
        ),
    ]
