# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0010_auto_20170517_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invoice_token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
