# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0011_profile_invoice_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_uri', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
