# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0012_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
