# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0013_profile_avatar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
