# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0014_profile_payment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_token',
        ),
    ]
