# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0015_auto_20170601_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proxy',
        ),
    ]
