# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0016_delete_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invoice_token',
        ),
    ]
