# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0017_remove_profile_invoice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_server_token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
