# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0019_auto_20170605_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
