# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0020_auto_20170605_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_user_id',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
