# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BunqAPI', '0021_auto_20170605_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_server_token_and_user_id',
            new_name='session_data',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_token',
            new_name='user_file',
        ),
    ]
