# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_ids', models.CharField(blank=True, max_length=20, null=True)),
                ('news_titles', models.CharField(blank=True, max_length=150, null=True)),
                ('together_titles', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
