# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunq_bot', '0003_auto_20170620_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TogetherUpdates',
            new_name='BunqTogether',
        ),
    ]
