# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naam', models.CharField(max_length=10)),
                ('Rekening', models.CharField(max_length=34)),
            ],
        ),
    ]
