# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_catagories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='Rekening',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
