# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20170407_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagories',
            name='Rekening',
        ),migrations.AddField(
        model_name='catagories',
        name= 'Rekening',
        field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), blank=True, size=None),
        
        )
    
    ]
