# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20170407_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='Naam',
            field=models.CharField(max_length=20),
        ),
    ]
