# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_delete_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='regex',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
