# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 16:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_auto_20170417_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='regex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
    ]
