# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_auto_20170417_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='Rekening',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='catagories',
            name='regex',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None),
        ),
    ]
