# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manager', '0010_auto_20170417_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalcatagories',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Naam', models.CharField(max_length=20)),
                ('Rekening', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=34), blank=True, null=True, size=None)),
                ('regex', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical catagories',
                'get_latest_by': 'history_date',
            },
        ),
    ]
