# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0011_historicalcatagories'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcatagories',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
